## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: org.apache.derby.jdbc.ClientDriver
    username: ecommerce
    password: ecommerce
    url: jdbc:derby://localhost:1527/ecommerce
    platform: derby
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database: derby
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
    database-platform: org.hibernate.dialect.DerbyDialect
  session:
    store-type: jdbc
server:
  servlet:
    contextPath: /api
